-- select e.NOM_ENTREPRISE, s.NOM_SECTEUR
-- from ENTREPRISE e, SECTEUR s, PARTICIPE p
-- where e.NUMERO_ENTREPRISE = p.NUMERO_ENTREPRISE and s.NOM_SECTEUR = p.NOM_SECTEUR
-- order by e.NOM_ENTREPRISE;

-- select e.NOM_ENTREPRISE, e.NOMBRE_SALARIES
-- from ENTREPRISE e
-- order by e.NOMBRE_SALARIES;

select e.NOM_ENTREPRISE, e.CODE_POSTAL_ENTREPRISE
from ENTREPRISE e
order by e.CODE_POSTAL_ENTREPRISE;

