SELECT E.NOM_ENTREPRISE AS ENTREPRISE, COUNT(*) AS NOMBRE_STAGE
FROM ENTREPRISE E, SALARIE S, STAGE F
WHERE E.NUMERO_ENTREPRISE = S.NUMERO_SALARIE 
AND S.NUMERO_SALARIE = F.NUMERO_SALARIE 
GROUP BY E.NOM_ENTREPRISE
ORDER BY NOMBRE_STAGE DESC;