drop table ELEVE cascade constraints;
drop table STAGE cascade constraints;
drop table ENTREPRISE cascade constraints;
drop table SECTEUR cascade constraints;
drop table TUTEUR cascade constraints;
drop table SALARIE cascade constraints;
drop table EST_CONTACT cascade constraints;
drop table PARTICIPE cascade constraints;
drop table AFFECTER cascade constraints;
commit;